### ISSUE TITLE
Don't ping everyone for donatebot please

### ISSUE THREAD

**Issue by melmsie** [DiscordBotList/issues#127]
#### Suggestion

Please don't ping everyone in the DBL server for donate bot shit. That's a great way to get people to mute everyone pings because that's not why we're there. Use donatebot's server for that please.

**Comment by sudomoose** [comment]
I agree, these pings are extremely offensive and have actually caused my pet ant to have a seizure.

**Comment by sudomoose** [comment]
Agreed, donatebot and dbl should stay separate, I know they're both made by the dbl team, but they're completely separate services. If anything, DonateBot pings would be more suited for the DSL server, as they're both for servers.

**Comment by bsantosh909** [comment]
+1

**Comment by BlazyDoesDev** [comment]
+1

**Comment by jczstudios** [comment]
Donate Bot is now suited for bots and servers!

**Comment by sudomoose** [comment]
The latest comment is unclear. Are Donate Bot pings not going to occur in the Discord Bot List server going forward or not?

**Comment by jczstudios** [comment]
There may be more pings but Donate Bot is no longer just for servers meaning the information is relevant to the Discord Bot List server.

**Comment by oliyy** [comment]
We agree we shouldn't ping everyone for all Donate Bot updates as that is not relevant for DBL. Only intended for a ping about the official release and this latest update because the update was only for bots and developers. We will not be pinging in the DBL server solely about Donate Bot from here forward. Sorry for the disturbance.
