### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by XenoCraftMC** [DiscordBotList/issues#198]
#### Suggestion

I think there should a progress tracker for the DBL applications.
**Reasons:**
- It will help people. _(literally self-explanatory)_
- People will stop bugging staff

#### Applicable Links or Attachments
_None_

**Comment by tonkku107** [comment]
Could you elaborate on what kind of trackers you mean

**Comment by XenoCraftMC** [comment]
> Could you elaborate on what kind of trackers you mean

I mean like:
**Kait**
ApplicationNumber (This shows the application number YOU have made. If i have 3 applications, it would show #3) : #1
Bot: yourBotHere
QueueNumber: #344
Status: Pending (Could be Pending, Declined or Accepted)

**Comment by tonkku107** [comment]
We have no intention to keep track of how many applications you've made.    
We've also decided a long time ago that we're not going to display where your bot is in the queue due to multiple reasons, including technical.    
You can already see the status (pending / approved) clearly on the bot page.
