### ISSUE TITLE
Suggestion: change how the voting cooldown works

### ISSUE THREAD

**Issue by T0TProduction** [DiscordBotList/issues#23]
Ive added an optional feature to remind people to vote when they can again to the bot.
Because of the cooldown lasting 24h, users not voting infinitely quick, and API response time (update that they have/havent voted) the reminder (and ability to vote) shifts back in time a bit day by day.
Essentially, even without reminder, users can *never* vote once per day, but once per 24h+their time to vote+something , probably one day less per month when summed over

Fix for that:
Make the vote cooldowm reset daily at a given time, e.g. every day 12pm EST

Therefore everyone can vote only once per day, but whenever they want and literally every day, which is not possible with the current method

**Comment by Oliyy** [comment]
We're not going to reset vote cooldowns at specific times every day because some younger aged users don't understand timezones that well. We are considering adding options like endpoints to check users time left before voting again. Furthermore, in the past week, the voting cooldown has changed to 12 hours.
