### ISSUE TITLE
Alt-account voting to get two spots shouldn't be allowed.

### ISSUE THREAD

**Issue by stageosu** [DiscordBotList/issues#325]
#### Suggestion

Being able to have a monopoly over a tag is totally unfair. I've spoken with a moderator several weeks ago about this and nothing's been done.

#### Applicable Links or Attachments

![Bot winning two spots with the same account, at the same price, on the same tag.](https://i.imgur.com/VvdYrqM.png)

**Comment by tonkku107** [comment]
Issues about auctions belong in #tester-bugs for now.

**Comment by xXxCake2019xXx** [comment]
Tonkku you literally do nothing even if we mention it in #tester-bugs mee6 has an alt that now outbids everyone on a 2nd account. This is totally unfair and I 100% agree with the OP. More and more people bitch about mee6 outbidding people and I was unfairly muted because I said " vinnie seems salty ".
