### ISSUE TITLE
HTML Tutorial 

### ISSUE THREAD

**Issue by Blue-Shun** [DiscordBotList/issues#65]
#### Suggestion

Can you please make a tutorial on editing the bot page via the HTML example:
- How to change title colour
- How to change the background

#### Applicable Links or Attachments

[Good HTML edited page](https://discordbots.org/bot/430969232134504448)

**Comment by zBlakee** [comment]
I would beg to differ that looking up a tutorial on how to properly use CSS and HTML would be more beneficial to you rather than us manually putting a "HTML tutorial" on the bot page. Not everyone wants to edit their page with HTML & CSS, and thus I don't think it's realistic or necessary to add a tutorial when its so easy to look up one online and suit it to your needs.

**Comment by ry0id** [comment]
yes

**Comment by ry0id** [comment]
blake and i do web development - hit us up if you need help, void#0001 + zBlake#0007

**Comment by devakira** [comment]
What I do is just look at devtools to figure out the item class names, it really isn't that hard.

**Comment by ry0id** [comment]
yes

**Comment by Oliyy** [comment]
This is not something we are going to implement at the moment. We might revisit this issue in the future.
